### ISSUE TITLE
Keys with spaces not correctly identified as yamlKey

### ISSUE THREAD

**Issue by vmizener** [stephpy/vim-yaml#21]
Current syntax rules do not identify keys with spaces, resulting in incorrect highlighting.

```yaml
foo: bar
foo bar:
  - foo: bar
  - foo bar: baz
```
![image](https://user-images.githubusercontent.com/31688407/73410146-3b9f5400-42b6-11ea-8c8a-f81223b80b15.png)
